Last last try

diff --git a/.github/workflows/pip-checks.yml b/.github/workflows/pip-checks.yml
--- a/.github/workflows/pip-checks.yml
+++ b/.github/workflows/pip-checks.yml
@@ -31,7 +31,7 @@ jobs:
       - name: Check no package is missing in setup.cfg
         run: |
           outputs=$(cat pip.txt)
-          if [[  == *"Package would be ignored"* ]]; then echo "::error title=MISSING-PACKAGES::Missing packages in setup.cfg"; exit 1; fi;
+          if [[ $outputs == *"Package would be ignored"* ]]; then echo "::error title=MISSING-PACKAGES::Missing packages in setup.cfg"; exit 1; fi;
 
       # Check import works
       - name: Check import works with base environment
