Try like this

diff --git a/.github/workflows/pip-checks.yml b/.github/workflows/pip-checks.yml
--- a/.github/workflows/pip-checks.yml
+++ b/.github/workflows/pip-checks.yml
@@ -32,12 +32,12 @@ jobs:
           outputs=$(python -m pip install -e . -vv 2>&1)
           echo $outputs
           
-      - name: Check not package is ignored
-        if: $outputs == *"Package would be ignored"*
-        uses: actions/github-script@v3
+      - name: Check no package is missing in setup.cfg
+        run: if [[ $output == *"Package would be ignored"* ]]; then echo "::error title=MISSING-PACKAGES::Missing packages in setup.cfg"; exit 1; fi;
+
+        uses: actions/github-script@v7
         with:
-          script: |
-            core.setFailed('Missing packages not declared in setup.cfg!')
+          script: core.setFailed('Missing packages not declared in setup.cfg!')
 
       # Check import works
       - name: Check import works with base environment
